### ISSUE TITLE
FsF-R1-01MD score earned for any value of object_type

### ISSUE THREAD

**Issue by ajaunsen** [pangaea-data-publisher/fuji#102]
Following the assessment of the following GUID:
https://su.figshare.com/articles/Data_for_Does_historical_land_use_affect_the_regional_distribution_of_fleshy-fruited_woody_plants_Arnell_et_al_2019_/10318046

the latest version of the FUJI tool scores success for test FsF-R1-01MD-1 with value "Stockholm University"?!

Shouldn't the value only be 'Dataset' or 'Collection'?

**Comment by huberrob** [comment]
This is a bug in the Embedded Dublin Core parsing..  will be fixed asap ...

**Comment by huberrob** [comment]
**DataCite: ResourceTypeGeneral:**

Audiovisual
Collection
DataPaper
Dataset
Event
Image
InteractiveResource
Model
PhysicalObject
Service
Software
Sound
Text
Workflow

**DC:Type:**

Collection
Dataset
Event
Image
InteractiveResource
MovingImage
PhysicalObject
Service, Software
Sound
StillImage
Text


**https://schema.org/**

CreativeWork
AmpStory
ArchiveComponent
Article
Atlas
Blog
Book
Chapter
Claim
Clip
Collection
ComicStory
Comment
Conversation
Course
CreativeWorkSeason
CreativeWorkSeries
DataCatalog
Dataset
DefinedTermSet
Diet
DigitalDocument
Drawing
EducationalOccupationalCredential
Episode
ExercisePlan
Game
Guide
HowTo
HowToDirection
HowToSection
HowToStep
HowToTip
HyperToc
HyperTocEntry
LearningResource
Legislation
Manuscript
Map
MathSolver
MediaObject
Menu
MenuSection
Message
Movie
MusicComposition
MusicPlaylist
MusicRecording
Painting
Photograph
Play
Poster
PublicationIssue
PublicationVolume
Quotation
Review
Sculpture
SheetMusic
ShortStory
SoftwareApplication
SoftwareSourceCode
SpecialAnnouncement
TVSeason
TVSeries
Thesis
VisualArtwork
WebContent
WebPage
WebPageElement
WebSite

**bioschemas.org**

BioChemEntity
BioSample
ChemicalSubstance
Gene
MolecularEntity
Protein
Taxon

**Comment by huberrob** [comment]
Now using schema.org types from jsonldcontext as well as the above listed DataCite and Dublin Core and bioschemas resource types as a reference list.
