### ISSUE TITLE
Test for inclusion of dataset/object identifier and that it resolves

### ISSUE THREAD

**Issue by ajaunsen** [pangaea-data-publisher/fuji#111]
FsF-F3-01M tests the inclusion of the data identifier. FsF-F1-01D +02D tests for dataset (object) GUID and PID, respectively.
FsF-F2-01M tests for core metadata, including the object_identifier.

It would make sense to also check that the object_identifier (if provided) resolves to the input GUID, unless the object_identifier matches the input. If this fails, it means there are alternative ways / identifiers to the same dataset and a warning may be issued?

**Comment by huberrob** [comment]
Sorry I have overlooked this issue. F-UJI already checks for includion of object_identifier in metadata but actually trusts that this is the correct one.  If e.g. a non  (1) PID URL is given and a (2) PID is discovered in the metadata, F-UJI uses this PID for further tests. But you are right it should be checked if then the PID resolves to the given URL (1)

**Comment by huberrob** [comment]
This is now tested in v1.0.6
