### ISSUE TITLE
PID handling, WAS: pubmed ids landing page

### ISSUE THREAD

**Issue by huberrob** [pangaea-data-publisher/fuji#115]
PMID:27184366

idutils recognises pmid but does not give a proper landing page URL

**Comment by kitchenprinzessin3880** [comment]
https://www.ncbi.nlm.nih.gov/pmc/tools/id-converter-api/

**Comment by huberrob** [comment]
Pubmed ids have not been included in our PID short list at  Mapper.VALID_PIDS

Actually I think we should not continue to use our list Mapper.VALID_PIDS but insteall use ALL the pids supported by idutils except urls..

**Comment by huberrob** [comment]
Here is a mapping table between IDUTILS and DataCite


DataCite |   | IDUTILS
-- | -- | --
ARK |   | ARK
arXiv |   | arXiv
bibcode |   | Bibcode
  |   | BioProject
  |   | BioSample
DOI |   | DOI
  |   | EAN8
EAN13 |   | EAN13
EISSN |   |  
  |   | Ensembl
  |   | GND
  |   | Genome Assembly
Handle |   | Handle
IGSN |   |  
ISBN |   | ISBN10
ISBN |   | ISBN13
  |   | ISNI
ISSN |   | ISSN
ISTC |   | ISTC
LISSN |   |  
LSID |   | LSID
  |   | ORCID
PMID |   | PubMed ID
  |   | PubMed Central ID
PURL |   | PURL
  |   | SRA
  |   | UniProt
  |   | RefSeq
UPC |   |  
URL |   | URL
URN |   | URN
w3id |   |

**Comment by huberrob** [comment]
To keep it simple, I just changed the list of valid pids:

VALID_PIDS = ['ark','arxiv','bioproject','biosample','doi', 'ensembl','genome','gnd','handle','lsid','pmid','pmcid','purl', 'refseq','sra','uniprot','urn']
