### ISSUE TITLE
Improve debug message of metadata parsing

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#116]
Some metadata standards will not have all properties required by F-UJI (e.g., dublin core-data link). if the data object to be tested uses this standard, then it should be clearly indicate that test was unsuccefful as the standard used does not have such a property.

**Comment by huberrob** [comment]
I think this is something which should be part of an individual assessment, F-UJI already indicates the metadata sources and it is quite tricky to build this feature in the moment. 
I will close this issue now, maybe we can revitalize this in a later version which ideally includes some more intelligence such as FAIR improvement suggestions.
