### ISSUE TITLE
Duplicate / repeated debug output in FsF-F2-01M

### ISSUE THREAD

**Issue by ajaunsen** [pangaea-data-publisher/fuji#131]
From this metric, it seems some of the debug output is repeated / duplicated. It may be a reason for this, but it would help to clarify with (even) better output :)

In the example below, the lines following "INFO: Trying to retrieve RDF metadata through content negotiation" are repeated after 5 lines.

INFO	Formats of structured metadata embedded in HTML markup - ['json-ld', 'opengraph', 'rdfa']
INFO	Could not identify Microdata metadata
INFO	RDFa metadata parsing exception, probably no RDFa embedded in HTML
INFO	Extract metadata from Schema.org JSON-LD (Embedded)
INFO	Found JSON-LD which seems to be valid, based on the given context type
SUCCESS	Found Schema.org metadata: dict_keys(['title', 'object_type', 'publication_date', 'modified_date', 'creator', 'publisher', 'summary', 'keywords', 'object_identifier', 'object_content_identifier'])
INFO	Checking for DublinCore metadata
INFO	Extract DublinCore metadata from html page
SUCCESS	Found DublinCore metadata: dict_keys(['object_identifier', 'object_type', 'title', 'publication_date', 'publisher', 'creator', 'keywords'])
INFO	Extract metadata from None
INFO	Found OpenGraph metadata
SUCCESS	Found OpenGraph metadata: dict_keys(['title', 'object_identifier', 'summary', 'object_type', 'publisher'])
INFO	Found object identifier in metadata, repeating PID check for FsF-F1-02D
INFO	Trying to retrieve XML metadata through content negotiation
INFO	Trying to access metadata from: https://dataverse.no/dataset.xhtml?persistentId=doi:10.18710/RIHOIE
INFO	Retrieving page https://dataverse.no/dataset.xhtml?persistentId=doi:10.18710/RIHOIE
INFO	Content negotiation accept=application/xml, text/xml;q=0.5, status=200
INFO	Found HTML page!
INFO	Extract metadata from Generic XML (Negotiated)
INFO	Expected XML but content negotiation responded: html
INFO	Trying to retrieve RDF metadata through content negotiation
INFO	Extract metadata from Linked Data (RDF)
INFO	Retrieving page https://dataverse.no/dataset.xhtml?persistentId=doi:10.18710/RIHOIE
INFO	Content negotiation accept=text/turtle, application/turtle, application/x-turtle;q=0.8, application/rdf+xml, text/n3;q=0.9, text/rdf+n3;q=0.9,application/ld+json, status=200
INFO	Found HTML page!
INFO	Expected RDF Graph but received - text/html
INFO	Extract metadata from Linked Data (RDF)
INFO	Retrieving page https://dataverse.no/dataset.xhtml?persistentId=doi:10.18710/RIHOIE
INFO	Content negotiation accept=text/turtle, application/turtle, application/x-turtle;q=0.8, application/rdf+xml, text/n3;q=0.9, text/rdf+n3;q=0.9,application/ld+json, status=200
INFO	Found HTML page!
INFO	Expected RDF Graph but received - text/html
INFO	Linked Data metadata UNAVAILABLE
INFO	Extract datacite metadata
INFO	Datacite metadata UNAVAILABLE
INFO	Type of object described by the metadata - Dataset
INFO	Testing for required core descriptive metadata elements ['creator', 'title', 'publisher', 'publication_date', 'summary', 'keywords', 'object_identifier', 'object_type']
SUCCESS	Found required core descriptive metadata elements ['creator', 'title', 'publisher', 'publication_date', 'summary', 'keywords', 'object_identifier', 'object_type']

**Comment by huberrob** [comment]
Yes I see... I think F-UJI is trying to do content negotiation on the PID URL as well as the landing page URL or the redirect page.. will check and correct
