### ISSUE TITLE
Metric/test proposal: PID persistency policy check

### ISSUE THREAD

**Issue by ajaunsen** [pangaea-data-publisher/fuji#132]
This is more in the nature of a proposed feature / metric / test, so it may be misplaced to report it here. It may be more relevant for the RDA metrics WG. Anyway, here it goes...

Among the PIDs supported by FUJI, for example DOI or Handle, there is nothing explicit to suggest the longevity of their persistency. About a year ago I made a suggestion to Datacite to add such a policy document, that would need to be machine-actionable. I am not sure they fully understood what I meant – to my understanding the persistency of a PID is generally assumed to be <persistent> based on the provider. I am not aware of an explicit policy document that states the longevity and persistency of the service. So to take DOI as an example, there should be a machine-actionable document that could be checked by an assessment tool to judge 'how' persistent it is according to the policy document, what the policy is for maintaining identifiers that no longer exist (deprecated) and probably other related factors too.

In my mind, this is NOT something the providers of datasets should worry about, but should rather be part of a look-up service of the PID provider, so for DOIs it should be Datacite or Crossref (I presume) and for Handle – not sure, I suppose the handle provider. So there should be some metadata about the DOI service (identified by the DO identifier prefix) that would point to a persistency policy, e.g. using a tag such as 'hasPersistencePolicy' that would allow PID providers to provide the link to the policy. The persistency policy itself would need to be machine-readable describing service provisioning times/periods, deprecation policies, how long metadata will be maintained, update/validation frequency etc.

Does this make sense to you? Are you aware of what, if any, of this is provided already by e.g. Datacite, Crossref or similar?

**Comment by huberrob** [comment]
I think this is rather about assessing the FAIR or TRUST status of a data repository. But otherwise I fully agree that once F-UJI could get this information e.g. from DataCite it could be integrated in the test . I just forwarded your comment to Sarala from DataCite.
