### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by ajaunsen** [pangaea-data-publisher/fuji#133]
The following DOs result in 'internal server error' 500

https://jyx.jyu.fi/handle/123456789/39205
https://jyx.jyu.fi/handle/123456789/36814
https://jyx.jyu.fi/handle/123456789/39234

while these do not:
https://jyx.jyu.fi/handle/123456789/63630
https://jyx.jyu.fi/handle/123456789/41648

Btw. the error is not indicated by the f-uji.net service.

**Comment by huberrob** [comment]
This was caused by  a new line char in one of the debug messages, which caused the logger handling to crash
