### ISSUE TITLE
RDFa exception error

### ISSUE THREAD

**Issue by ajaunsen** [pangaea-data-publisher/fuji#143]
Hello!
I am getting this error on all tested DOs from these (and more) repositories:

http://tun.fi/MX.1
http://id.herb.oulu.fi/GAL.1
http://id.luomus.fi/GP.110472

It seems this code is either misinterpreting some content for RDFa or this is a generic problem with many repositories. 
I wonder if there is a better way to make this test or if the library (rdflib?) could be improved to be more robust and specific in its exception handling?

**Comment by huberrob** [comment]
This is a debug message which I probably should not include in the log in the future... 
You can ignore this error, it is indicating that rdflib is trying to parse the HTML but fails due to some unexpected code - which means that no RDFa is available.
