### ISSUE TITLE
Content negotiation and over all scores

### ISSUE THREAD

**Issue by ajaunsen** [pangaea-data-publisher/fuji#144]
Hello!

For the following dataset:
http://id.luomus.fi/GP.110472

I get a total score with v.1.0.6 of 29% over all score. FsF-F2-01M fails with 0 of 2 score points due to missing core metadata.

This repository supports content negotiation and F-UJI seems to find RDF+XML (RDF Graph?):

> Trying to retrieve RDF metadata through content negotiation
> Retrieving page https://laji.fi/in/view?uri=http%3A%2F%2Fid.luomus.fi%2FGP.110472
> Content negotiation accept=text/turtle, application/turtle, application/x-turtle;q=0.8, application/rdf+xml, text/n3;q=0.9, text/rdf+n3;q=0.9,application/ld+json, status=200
> Ignoring HTML response
> Expected RDF Graph but received -: text/html
> Retrieving page http://id.luomus.fi/GP.110472
> Content negotiation accept=text/turtle, application/turtle, application/x-turtle;q=0.8, application/rdf+xml, text/n3;q=0.9, text/rdf+n3;q=0.9,application/ld+json, status=200
> Try to parse RDF from -: http://id.luomus.fi/GP.110472
> Found RDF Graph
> Trying to query generic SPARQL on RDF
> Found some metadata elements through generic SPARQL query on RDF -: dict_keys(['object_identifier', 'title', 'publisher', 'publication_date', 'object_type'])
> 

It is unclear to me if this negotiated content is the same as that provided when the RDFXML format-specification is provided:

http://id.luomus.fi/GP.110472?format=RDFXML

Assessment of this DO seems to find the same metadata in FsF-F02-01M, but the over all score is 33% (as opposed to 29%).
This is due to the fact that the tool now considers the RDF+XML content in all tests, so tests FsF-F4-01M and FsF-I1-01M pass with higher score. Oddly,  FsF-R1-01MD does not due to the object_type not being identified when providing the format?RDFXML

**Comment by huberrob** [comment]
F-UJI is testing for embedded RDF within the landing page (score=1) and those delivered by content negotiation (score =1).
In your case http://id.luomus.fi/GP.110472?format=RDFXML, F-UJI was ignoring the content type of the landing page (rdf-xml instead of html) which actually is a bug and caused F-UJI to score the same RDF twice.
I will fix this
