### ISSUE TITLE
Document user management for local installations

### ISSUE THREAD

**Issue by sneumann** [pangaea-data-publisher/fuji#156]
Hi, when running a local fuji REST, it is needed to add allowed users to
https://github.com/pangaea-data-publisher/fuji/blob/master/fuji_server/config/users.py
in the form of (gasp!) `fuji_users = {"username": "password"}`.
Alternatively, for an internal fuji server one could disable the basic auth entirely in 
https://github.com/pangaea-data-publisher/fuji/blob/master/fuji_server/yaml/swagger.yaml#L89
Yours, Steffen

**Comment by huberrob** [comment]
This is a good idea, once I find the time I will look at this ;)

**Comment by sneumann** [comment]
No hurry, partly solved by the issue itself :-) Yours, Steffen
