### ISSUE TITLE
CETAF PID support requested by a community of biodiversity repositories

### ISSUE THREAD

**Issue by ajaunsen** [pangaea-data-publisher/fuji#158]
Hello,
In EOSC-Nordic we are meeting with some of the repositories and one such community (FinBIF, laji.fi) within the domain of biodiversity, species observations). First question is about their use of PIDs. They are using the community recommended CETAF:
https://cetaf.org/cetaf-stable-identifiers

also described here:
https://cetafidentifiers.biowikifarm.net/wiki/Main_Page

which is being used by 14 member institutions.

This is not supported by F-UJI and I wonder if you are familiar with these identifiers or have previously considered incorporating them? ... or are they suitable for inclusion in F-UJI?

I have pointed out to them that in any case they are providing the URL to the dataset as the object identifier.
Here is an example:
http://id.luomus.fi/GP.110472
Pressing 'Show extra info' in upper right corner gives:
https://laji.fi/en/view?uri=http:%2F%2Fid.luomus.fi%2FGP.110472
and clicking next to 'Collection' gives:
https://kotka.luomus.fi/view?uri=HR.22

which contains more metadata which is not found by F-UJI.

The problem here is that the metadata is not found by the machine / F-UJI and I wonder if you have recommendations on how they best could address this in their case? using HTTP signposting possibly?

Andreas

**Comment by huberrob** [comment]
Dear Andreas,

yes I know CETAF identifiers. The problem with them is that they do not require to comply with any pattern or synthax except the URI rules. This makes it impossible to differentiate them from regular URI (URL) and therefore F-UJI cannot detect them.
CETAF states these identifiers to be 'stable' but not 'persistent' I know this is a semantically subtile difference ...
In addition, I fear CETAF identifiers do not comply with the EOSC PID policy which requires some governance and management of PID systems.

best regards,
Robert

**Comment by huberrob** [comment]
Dear Andreas,

regarding the example http://id.luomus.fi/GP.110472 F-UJI already dscovers the RDF, but unfortunately this is including several entities in a Graph/ Format:


```
<rdf:Description rdf:about="http://id.luomus.fi/GP.110472">
<rdf:type rdf:resource="http://rs.tdwg.org/dwc/terms/Event" />
<dc:type rdf:resource="http://purl.org/dc/dcmitype/Event" />
<dc:identifier>http://id.luomus.fi/GP.110472</dc:identifier>
<dwc:catalogNumber>http://id.luomus.fi/GP.110472</dwc:catalogNumber>
<dc:publisher>http://gbif.fi</dc:publisher>
<dc:bibliographicCitation>Finnish Biodiversity Information Facility (http://gbif.fi), http://id.luomus.fi/GP.110472, accessed via Finnish Biodiversity Information Facility (FinBIF), Creative Commons Attribution</dc:bibliographicCitation>
<dwc:institutionCode>TODO</dwc:institutionCode>
<dwc:collectionCode>Hymenoptera Eastern Fennoscandia (Luomus)</dwc:collectionCode>
<dc:modified>2020-09-09</dc:modified>
<dc:created>2020-09-09</dc:created>
<dc:title xml:lang="en">Event http://id.luomus.fi/GP.110472</dc:title>
<rdfschema:comment xml:lang="en">Describing the event (summary data)</rdfschema:comment>
<dc:hasPart rdf:resource="http://id.luomus.fi/MY.9179872" />
 </rdf:Description>
<rdf:Description rdf:about="http://id.luomus.fi/MY.9179872">
etc..
```

F-UJI takes the first one which is the 'Event' entity. If they wish to provide more metadata, they simply could add this to the RDF, using dc:terms. Is this an option?

best regards,
Robert

**Comment by huberrob** [comment]
Unless CETAF identifiers can be identified by synthax or registry this cannot be resolved, I am closing this issue now
