### ISSUE TITLE
Unable to connect to the server 

### ISSUE THREAD

**Issue by TigerLeap39** [pangaea-data-publisher/fuji#170]
Hello!

We'd like to use your tool in our research. Nontheless it doesn't start.

Followng the steps we buit the Docker (seemed without errors). 
```{python}
docker build -t fuji .
docker run -d -p 1071:1071 fuji
```
The second command gives me this `7fa4686b3c6e5e070e850956df724c806bed77964ca77c59815f9665f66353dd`. 
And with  `docker ps` it does'nt show any docker running.
Same here with Swagger user interface url `http://localhost:1071/fuji/api/v1/ui/`  no connection.

Is there anything I might have missed during the installation?

**Comment by wilkos-dans** [comment]
Hi there!
Try to add `tldextract~=3.1.0` to /requirements.txt.
I created a PR for this: https://github.com/pangaea-data-publisher/fuji/pulls
Thanks.

**Comment by huberrob** [comment]
Thanks Wilko!

**Comment by wilkos-dans** [comment]
Hi, @TigerLeap39, I also tested the image and it is OK now. If you start the container as described, you can tail the logs: `docker logs fuji --follow`.
Within the EOSC Synergy project task3.3 we are using a containerized FUJI image as part of the FAIR assessment pipeline.
@huberrob thanks for merging!

**Comment by TigerLeap39** [comment]
Thanks a lot @wilkos-dans, it works! 👍 
Thanks for the quick reply!
