### ISSUE TITLE
Bug - FsF-F4-01M-2

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#172]
Dataset tested: https://doi.org/10.1594/PANGAEA.922034
The dataset is discoverable via Datacite: https://search.datacite.org/works?query=+Hyperspectral+underwater+light+field+measured+during+the+cruise+MSM21%2F3+with+RV+MARIA+S+MERIAN
However, the assessment report indicates that 

WARNING | Metadata is NOT found through registries considered by the assessment service -: ['Datacite Search']
-- | --

<img width="1130" alt="Screen Shot 2021-06-14 at 9 55 44 am" src="https://user-images.githubusercontent.com/11935313/121825610-c4c1fa00-ccf6-11eb-96a1-5982dd90b2a8.png">

**Comment by huberrob** [comment]
Don't think this is a F_UJI issue: Datacite returns a 404 not found error.. maybe the service is down.. anyway this test needs to be redesigned in order to test registration at e.g. Google  dataset
