### ISSUE TITLE
Create search engine helpers

### ISSUE THREAD

**Issue by huberrob** [pangaea-data-publisher/fuji#173]
While most data set search engines do not offer APIs (Google data set serahc) we need to be prepared to query these registries by PID. Therefore some new helper classes are requires, for example for:

- DataCite registry
- Google data set search
- EUDAT B2FIND
- etc

**Comment by huberrob** [comment]
More candidates:

https://data.mendeley.com/ ->  https://api.datasearch.elsevier.com/api/v2/search?query=DOI%28%7B10.1594%2FPANGAEA.81110%7D%29%20


OpenAire

**Comment by huberrob** [comment]
Added support for the following search engines/catalogs:
- Google data set search using the data set at :https://www.kaggle.com/googleai/dataset-search-metadata-for-datasets
- Datacite registry
- Mendeley data

**Comment by coret** [comment]
Candidate: https://datasetregister.netwerkdigitaalerfgoed.nl/?lang=en / https://triplestore.netwerkdigitaalerfgoed.nl/sparql (DCAT datasetdescription of Dutch heritage datasets via SPARQL)
