### ISSUE TITLE
Community vs Multidicipline

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#18]
https://rdamsc.bath.ac.uk/subject/Multidisciplinary

Are multidisciplinary metadata standards accepted as community-endorsed standards in the context of FAIR?

**Comment by kitchenprinzessin3880** [comment]
@huberrob any idea?

**Comment by kitchenprinzessin3880** [comment]
added method to derive standards from re3data and also from oai-pmh endpoint listed in re3data. multidiciplinary standards are not considered as part of test 'community-endorsed metadata'

**Comment by huberrob** [comment]
I do not think there is a common agreement on what a multidiciplinary metadata standard actually is. There are some authoritative recommendations:

- https://www.w3.org/TR/dwbp/#metadata -> Dublin Core and DCAT is mentioned.
- https://www.w3.org/2017/dxwg/wiki/DCAT_Context -> is very DCAT centric but mentions DDi, DC, ISO19115, etc
- https://rd-alliance.github.io/metadata-directory/standards/ -> a nice RDA collection
- https://github.com/EOSC-EDMI/eosc-edmi.github.io/blob/master/resources/eoscpilot-d6.3.pdf -> EOSC they seem to prepare EDMI metadata guidelines but hard to understand on what this is based on..

**Comment by huberrob** [comment]
Despite these standards are not relevant for community driven metadata they are very relevant for all our generic assessments. I therefore reopen the issue unless we have decided on the set of metadata standards we support in the first release.

**Comment by kitchenprinzessin3880** [comment]
i prefer to use the terms domain-agnostic and domain-specific
