### ISSUE TITLE
FsF-A1-01M - what structure is expected for access rights?

### ISSUE THREAD

**Issue by kburger** [pangaea-data-publisher/fuji#183]
My metadata contains a `dcterms:accessRights` statement, linking to a resource typed as `dcterms:RightsStatement`, with (in some cases) a `dcterms:description` explaining in human readable language. Test `FsF-A1-01M` fails on all three sub-tests, where I would expect at least `-1` and possibly `-2` to pass the test. Is there a specific structure that `FsF-A1-01M` assumes the metadata to follow?

A barebones example of the structure:
```turtle
<PID> dcterms:accessRights <PID#rights> .
<PID#rights> a dcterms:RightsStatement ;
    dcterms:description "human readable text here" .
```

**Comment by huberrob** [comment]
Ideally you indicate access rights using one of he following controlled vocabularies:
 
- http://vocabularies.coar-repositories.org/documentation/access_rights/
- http://www.ukoln.ac.uk/repositories/digirep/index/Eprints_AccessRights_Vocabulary_Encoding_Scheme
- http://publications.europa.eu/resource/authority/access-right
- https://guidelines.openaire.eu/en/latest/data/field_rights.html
