### ISSUE TITLE
FsF-A1-03D - which standardized web communication protocols are supported?

### ISSUE THREAD

**Issue by kburger** [pangaea-data-publisher/fuji#184]
Test `FsF-A1-03D` fails on a FAIR Data Point metadata resource that contains a DCAT Dataset entity. The resource in question is `http://purl.org/fairdatapoint/app/dataset/764fc18f-9b8d-4e1f-857f-b12b194e048f`. Since `FsF-A1-03D-1` mentions  it tries to resolve a link based on "standardized web communication protocols" I wonder what those protocols are. The data is in the DCAT case linked through a DCAT Distribution resource.

**Comment by huberrob** [comment]
the usual ones: here is the dictionary 
F-UJI is using: 

`{"ftp": "File Transfer Protocol",
  "http": "Hyper Text Transfer Protocol",
  "https": "Hyper Text Transfer Protocol Secure",
  "rtsp": "Real Time Streaming Protocol",
  "rtspu": "Real Time Streaming Protocol",
  "sftp": "Secure File Transfer Protocol",
  "shttp": "Secure Hypertext Transfer Protocol",
  "svn": "Subversion",
  "ssh": "Secure Shell",
  "telnet": "Telnet",
  "ws": "WebSocket",
  "wss":"WebSocket Secure"}`

**Comment by huberrob** [comment]
So all you have to do is to provide a valid  URI which uses one of the above mentioned schemes
