### ISSUE TITLE
FsF-I3-01M - how are related entities determined?

### ISSUE THREAD

**Issue by kburger** [pangaea-data-publisher/fuji#185]
Test `FsF-I3-01M` fails on a FAIR Data Point metadata resource that contains a DCAT Dataset entity. The resource in question is `http://purl.org/fairdatapoint/app/dataset/764fc18f-9b8d-4e1f-857f-b12b194e048f`. Is there a certain property assumed to indicate related entities?

**Comment by huberrob** [comment]
Here F-UJI is following most DCTERMS subproperties of relation:

'references' ,'source' ,'isVersionOf','isReferencedBy','isPartOf','hasVersion','replaces', 'hasPart', 'isReplacedBy', 'requires', 'isRequiredBy'

I have seen that some of them were not checked in v1.3.2 I just fixed this..
