### ISSUE TITLE
FsF-R1-01MD - data content in a DCAT model

### ISSUE THREAD

**Issue by kburger** [pangaea-data-publisher/fuji#186]
My metadata describes a DCAT Dataset. When evaluating the resource, test `FsF-R1-01MD` fails on a number of sub-tests. Among others, `FsF-R1-01MD-2a` fails with the test name being "File size and type information are specified in metadata". In the DCAT model, this data is described in the Distribution linked to the Dataset. I would assume `FsF-R1-01MD` traverses the link into the Distribution and discovers the distribution metadata there.

**Comment by huberrob** [comment]
F-UJI tries to identify a **dcat:Distribution** and then expects a **dcat:accessURL** (think I need also to check for **dcat:downloadURL**) which contains the link to the file, you should also give info on the file type using **dcat:mediaType** (ideally mime type) and file size using **dcat:bytesSize**

At least this is how most DCAt datasets I have seen use it, see also : https://www.w3.org/TR/vocab-dcat-2/#a-dataset-available-as-download-and-behind-some-web-page

**Comment by huberrob** [comment]
But this case was not covered yet,  I think this is what you are looking for?
```
:dataset-004
  rdf:type dcat:Dataset ;
  dcat:distribution :dataset-004-csv ;
  dcat:distribution :dataset-004-png ;
```

**Comment by kburger** [comment]
> But this case was not covered yet, I think this is what you are looking for?
> 
> ```
> :dataset-004
>   rdf:type dcat:Dataset ;
>   dcat:distribution :dataset-004-csv ;
>   dcat:distribution :dataset-004-png ;
> ```

Correct, my `dcat:Dataset` resource links out to (in almost all cases) one or more `dcat:Distribution` resources. Example instance available here: https://fairsfair.fair-dtls.surf-hosted.nl/dataset/043ea683-a3e4-441e-b8de-d376b5a9991f

**Comment by kburger** [comment]
Version `1.3.4b` currently still fails on `FsF-R1-01MD-2`, specifically:

`FsF-R1-01MD-2a` - file size and type information are provided in the `dcat:Distribution`, through the `dcat:byteSize` and `dcat:mediaType` statements

**Comment by huberrob** [comment]
I have seen that you link from https://fairsfair.fair-dtls.surf-hosted.nl/dataset/043ea683-a3e4-441e-b8de-d376b5a9991f in dcat:distribution 
to  https://purl.org/fairdatapoint/app/distribution/584d514f-cb00-4a3d-9f41-2cad12549061
which then contains the information you mentioned.

Please note that F-UJI is not able to perform distributed queries. F-UJI just checks the information given in a single RDF etc identified. Then it verifies if a dcat:Dataset can be identified in this RDF and analyses associated tuples found there.

You might consider to include distribution info within the dcat:Dataset resource instead of linking to external resources.
In general I would recommend to go the easy way instead of complex nesting and linking.

**Comment by kburger** [comment]
https://fairsfair.fair-dtls.surf-hosted.nl/dataset/043ea683-a3e4-441e-b8de-d376b5a9991f links to https://fairsfair.fair-dtls.surf-hosted.nl/distribution/936255c5-8fa4-4843-a01c-05fd5f033dca, a `dcat:Distribution` contained within the same FAIR Data Point. Sure, this can be considered an 'external' resource, as in not contained within the same rdf blob. But that seems a reasonable way of structuring the data, right? Would fuji be able to resolve the resources to gather the information needed for the test this way?

**Comment by huberrob** [comment]
Apologizes, but unfortunately in the moment F-UJI is not able to resolve these linked resources. I can take a look into this but this is probably going to be resolved after the summer break.

**Comment by huberrob** [comment]
Ok, this was not so complicated.. it should work now.

**Comment by huberrob** [comment]
@kburger I think DCAT-2 like linked data content is now supported by F-UJI v.1.5.3 see f-uji.net . Can you please test and confirm?
