### ISSUE TITLE
FsF-R1.1-01M - purl.org/NET/rdflicense is not recognised

### ISSUE THREAD

**Issue by kburger** [pangaea-data-publisher/fuji#187]
Test `FsF-R1.1-01M` fails on a FAIR Data Point metadata resource that contains a DCAT Dataset entity. The resource in question is `http://purl.org/fairdatapoint/app/dataset/764fc18f-9b8d-4e1f-857f-b12b194e048f`. It contains a statement for `dcterms:license` where the object is a license from the `purl.org/NET/rdflicense` vocabulary. `FsF-R1.1-01M-1` does not seem to recognise entries from this vocabulary.

**Comment by huberrob** [comment]
Agree, puristically PURLs use the http scheme but since purl resolver also resolve https this should be fixed
