### ISSUE TITLE
Unresolved PIDs

### ISSUE THREAD

**Issue by ajaunsen** [pangaea-data-publisher/fuji#200]
All the following PIDs seem to not resolve and it is not clear from the F-UJI (v1.3.5 + 1.3.5b) output what goes wrong?!

10.1371/journal.pone.0083351.t003
10.23698/aida/mbtst-dm
10.15155/re-10
10.15155/re-11
10037.1/10211
10037.1/10152
10037.1/10040

Andreas

**Comment by ajaunsen** [comment]
... and here an example of a GUID/URL:
https://gerda.geus.dk/Gerda/dataset/show/705151

**Comment by huberrob** [comment]
Dear Andreas,

it seems all these PIS just dont resolve and servers e.g. return a 404 not found message or similar.
I could imagine to introduce an additional logging message level  (e.g. ALERT) which indicates such external service failures. These could then be displayed and analysed separately. What do you think?

best regards,
Robert

**Comment by ajaunsen** [comment]
Yes, an alert would be good. In v1.1.2 and earlier the error code (404) was also listed in the output which we used to trigger an internal alert.
