### ISSUE TITLE
Create basic python package (dev) features

### ISSUE THREAD

**Issue by broeder-j** [pangaea-data-publisher/fuji#215]
(Maybe) Enable the following

- [ ] github CI with basic test environment (See if the fuji_instance can be mocked, that all the other things can be tested)
- [ ] pre-commit check, to catch easy dev mistakes and enforce consistent code style
- [ ] enable type check?
- [ ] basic documentation (sphinx?) with at least an autogenerated module & and function doc. As static html pages which can be embedded and hosted where ever. I have seen f-uji.net got some more information (docs), which could also be put under docs.
- [ ] more metadata in setup.py, merge requirements.txt into setup.py. Any reason not to do this? Or is this for a fixed environment
- [ ] In the current install there is some issue with some sub dependency
- [ ] The special cpython version because of urllib could be specified with a pyproject.toml
- [ ] basic version consistency check, or is the current version in setup.py and FUJI_VERSION supposed to differ?
- [ ] create an authors file with contribution info
- [ ] auto release upload to pypi, Also zenodo if wanted? i.e. add .zenodo.json file (to docker image upload exists by now)

@huberrob: any hard opinions here, otherwise I just do this and you can review the (several) pull request(s)

**Comment by huberrob** [comment]
Sorry for not responding earlier, I have not seen you are waiting for my OK...
But yes, please go ahead and try to implement as much as you can ;)
