### ISSUE TITLE
Modularize the server, harvesting and scoring code

### ISSUE THREAD

**Issue by broeder-j** [pangaea-data-publisher/fuji#217]
Currently the server, harvest is entangled with the scoring evaluation.
Can this be changed? (I.e does the score metric depend on on the fly harvest features and not only metadata)

ideally we would end up with a part doing all the requests, a part with client code, and a part with score calculation code, I.e that a score can be calculated by some given metadata object or whatever containing the harvested metadata information.

Benefits: easier development, testing and metric adjustments. Also this would allow one to use fuji scoring and other features as a library. It would also create more flexibility, I.e one can evaluate the fair score of different metadata exports which a repository provides.

(I will let you know when we start working on this.) 
By then I have some more concrete proposal on how this may be done.

I put this here now for discussion

**Comment by huberrob** [comment]
This would be really useful, in addition, I am also thinking about harmonizing the swagger outputs so we would ideally have less classes to care of.

Maybe you can make a proposal on a future structure, e.g. required classes and methods so we can define a template and proceed with this?
