### ISSUE TITLE
Speed up usage of google dataset data

### ISSUE THREAD

**Issue by broeder-j** [pangaea-data-publisher/fuji#218]
currently searching for a pid in the google dataset is slow. 
One way to speed up is to parse it into a local sqlite db or something which creates an search index, so that the pids can be accessed faster.

(nice to have, scaleing)

The same my apply to other larger metadata sets

**Comment by huberrob** [comment]
Yes this is indeed painful, unfortunately Google Dataset Search does not offer an API and the Kaggle snapshot is very outdated.

**Comment by huberrob** [comment]
Use of SQLite instead of list searching speeds search and reduces memory usage dramatically, I currently work on this and will commit asap
