### ISSUE TITLE
Add examples and utils around f-uji use cases

### ISSUE THREAD

**Issue by broeder-j** [pangaea-data-publisher/fuji#219]
for example a script to evaluate several urls, and to create a report as an html or pdf.

There are code snippets all over the place of this for example in the client folder.

**Comment by TigerLeap39** [comment]
Hi! Sorry I'm new using f-uji.
A quick question.
I have 200 urls to assess. Can I assess them inside the tool interface, or I have to execute the  `fuji_mass_eval_template.py` script?

Thanks in advance.

**Comment by huberrob** [comment]
It is not possible to submit a list of URIs/PIDs to the F-UJI API. You will therefore have to run API calls in a loop, so the fuji_mass_eval_template.py script may help you here.

**Comment by TigerLeap39** [comment]
Thank you!
