### ISSUE TITLE
Re3data metadata standards entries do not contain correct schema or namespace URL

### ISSUE THREAD

**Issue by huberrob** [pangaea-data-publisher/fuji#23]
Unfortunately re3data does not give back e.g. schema location URL as we would expect this for XML schemas like ABCD or DC, it instead links to a dcc.ac.uk catalogue entry.

This is a problen since the unique identifier for a XML schema surely is its schema location or namespace.

Example out put from Re3data:

<r3d:metadataStandard>
<r3d:metadataStandardName metadataStandardScheme="DCC">ABCD - Access to Biological Collection Data</r3d:metadataStandardName>
<r3d:metadataStandardURL>http://www.dcc.ac.uk/resources/metadata-standards/abcd-access-biological-collection-data</r3d:metadataStandardURL>
</r3d:metadataStandard>

**Comment by huberrob** [comment]
can be completed in: metadata_standards.json

**Comment by kitchenprinzessin3880** [comment]
yes, therefore for community-driven schema, the match is done suing the metadata name, not ['creator', 'title', 'object_identifier', 'publication_date']

**Comment by huberrob** [comment]
I think we can close this issue now since we have our own namespace lists..
