### ISSUE TITLE
Module 'jsonschema_utils' has no attribute 'types_msg' error

### ISSUE THREAD

**Issue by Dmusulas** [pangaea-data-publisher/fuji#231]
# Issue 
While experimenting with development server hosted locally, I tried to POST /evaluate the provided data set (_DOI: https://doi.org/10.1594/PANGAEA.908011_). This return internal server error (500) last error seems to be:
`File "~\fuji\venv\lib\site-packages\connexion\json_schema.py", line 65, in validate_type 
    yield ValidationError(_utils.types_msg(instance, types))  
AttributeError: module 'jsonschema._utils' has no attribute 'types_msg'
`

**Full traceback here:** https://pastebin.com/UjRAhXjG
## Setup
The fuji_server is running on local Windows 10 machine with Python 3.10 and all the required packages installed on venv. Everything except pandas was successfully installed with `pip install -r requirements.txt`. Pandas did not what to build on wheel for some reason, so installed it manually.  

I have also tried to launch fuji server with Docker but trying to evaluate result in the same error.
## Reprex
1. Followed all the installation instructions
2. Successfully launched the server 
3. Accessed it via Swagger interface  
4. Tried to evaluate provided dataset and several other DOIs
5. Got 500 internal error in both console and Swagger
Request is default one below:
`
{
  "metadata_service_endpoint": "http://ws.pangaea.de/oai/provider", 
  "metadata_service_type": "oai_pmh", 
  "object_identifier": "https://doi.org/10.1594/PANGAEA.908011",
  "test_debug": true, 
  "use_datacite": true}
`

**Comment by huberrob** [comment]
Can you please check which jsonschema etc. version oi have on your computer? Can you send e.g. the output of pip list ?

**Comment by Dmusulas** [comment]
I have jsonchema version 4.2.1 installed, I believe it is the newest release. The output of [pip list](https://pastebin.com/g7d5ZCjz)

**Comment by huberrob** [comment]
Ok, so please downgrade to jsonschema 3.2.0 

See also:

https://github.com/zalando/connexion/issues/1430
