### ISSUE TITLE
Test test_fair_check() is failing because of mismatched metrics 

### ISSUE THREAD

**Issue by videbar** [pangaea-data-publisher/fuji#235]
The test `test_fair_check()` in the `test_fair_check.py` file seems to be performing an evaluation on the repository `https://doi.org/10.1594/PANGAEA.902845` and comparing the resulting score with reference values in `tests/controllers/json_ref_data/10.1594_PANGAEA.902845_sum.json`.

The problem is that the FAIR score of the repository seems to have changed and it no longer correspond with the reference, which is causing the test to fail.

**Comment by huberrob** [comment]
sometimes 3d party services used by F_UJI are down e.g.  datacite content negotiation is down which influences the assessment results. I fear we'll need different test targets.
