### ISSUE TITLE
Remove PyPi installation from section "Python module-based installation"

### ISSUE THREAD

**Issue by afuetterer** [pangaea-data-publisher/fuji#240]
Hi,

in the README.md under "Python module-based installation" there is a line saying "Alternative you can install the latest F-UJI release on PyPI". If you run `pip install fuji` you actually end up installing this other [package](https://pypi.org/project/fuji/). Maybe just remove that line, if there is no plan on releasing this project on PyPi?

Thanks for the great tool!

**Comment by huberrob** [comment]
Yes indeed this is indeed very confusing. Thanks for the hint!
