### ISSUE TITLE
Question about "repodois.json" and "retrieve_datacite_re3repos"

### ISSUE THREAD

**Issue by afuetterer** [pangaea-data-publisher/fuji#245]
Hi, I have a quick question:
If F-UJI finds a DataCite client id in the response from DataCite's API, it then looks up a re3data-DOI in the dictionary in [repodois.json](https://github.com/pangaea-data-publisher/fuji/blob/master/fuji_server/data/repodois.json), correct?
If there is no mapping between client id and re3data DOI in the JSON file, the re3data-lookup fails, right?
Should we add known mappings per PR then?

**Comment by huberrob** [comment]
Yes, this can be done but please also add/propose these mappings at re3data.org using their 'submit a change request' method.

**Comment by afuetterer** [comment]
Thank you. How would you add the DataCite client id to re3data? Can you give an example of a repository, that already has the client id in its metadata?
