### ISSUE TITLE
Tagging versions

### ISSUE THREAD

**Issue by afuetterer** [pangaea-data-publisher/fuji#247]
Hi,
could you add tags for the newer versions? I saw in the commits, that you are now at 1.4.6, but there is only 

- https://github.com/pangaea-data-publisher/fuji/releases/tag/v.1.4.3
- https://github.com/pangaea-data-publisher/fuji/releases/tag/v.1.3.5
- ...

Regarding the pip installation (#240 ), since version 1.4.3 you actually can install the project directly from GitHub, via:
`
pip install git+https://github.com/pangaea-data-publisher/fuji.git@v.1.4.3#egg=fuji
`
or latest commit from master:
`
pip install git+https://github.com/pangaea-data-publisher/fuji.git@master#egg=fuji
`
Though you need to create your own server.ini locally then.

Also, is there a way to tag these Docker images? There is only the tag latest and then untagged versions, correct? As some of these commits/builds are broken, it would be nice to be able to specify which version to install.

Thanks.

**Comment by huberrob** [comment]
1.4.6 is released now: https://github.com/pangaea-data-publisher/fuji/releases/tag/v.1.4.6
