### ISSUE TITLE
Metrics YAML File

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#25]
1. New version should be created and include the objects metrics descriptions from v3.0.
2. Add assessment aspects for each metric.
3. Update server.ini file

**Comment by huberrob** [comment]
@kitchenprinzessin3880 I think we can close this issue?

**Comment by kitchenprinzessin3880** [comment]
the assessment mechanism is not yet covered in yaml.

**Comment by huberrob** [comment]
OK I finally started this.. 

Example:

  evaluation_mechanism: A persistent identifier is considered to be valid if the given identifier complies with a valid PID synthax. To be valid, the PID further has to be resolvable.
  evaluation_criteria:
    - criterium_identifier: FsF-F1-02D-1
      criterium_name: Identifier follows an idutils defined persistent identifier synthax
      criterium_score: 0
    - criterium_identifier: FsF-F1-02D-1b
      criterium_name: Persistent identifier is resolvable
      criterium_score: 1

**Comment by huberrob** [comment]
done..
