### ISSUE TITLE
Assessment UI f-uji.net available (source code)? 

### ISSUE THREAD

**Issue by ignpelloz** [pangaea-data-publisher/fuji#255]
Hi,

is the source code from https://www.f-uji.net/index.php?action=test publicly available? it would be great to have that UI when deploying F-UJI, alongside the Swagger one. Specifically, the results view would be useful, as it shows the results in a very clear and user friendly way (instead of JSON). For example:  https://www.f-uji.net/view/109

Thanks!
Ignacio

**Comment by huberrob** [comment]
Not yet, there are some license etc. issues I need to resolve, I will check if I can release the view script at least. But there is also another very good (better?) F-UJI web client available here: https://github.com/MaastrichtU-IDS/fairificator

**Comment by ignpelloz** [comment]
Great, thanks! we will have a look.
