### ISSUE TITLE
New Markupsafe 2.1.0 version is breaking F-UJI

### ISSUE THREAD

**Issue by ignpelloz** [pangaea-data-publisher/fuji#257]
Hi, 

Flask uses Jinja2, which uses MarkupSafe. On February 17th, MarkupSafe 2.1.0 was released, where `soft_unicode` has been replaced by `soft_str` (https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0).

This new version of Markupsafe is breaking F-UJI. Jinja2 should be updated from v2 to v3, however that conflicts with Flask as F-UJI uses Flask's 1.1.4 which requires Jinja2<3.0 and >=2.10.1.

@huberrob in principle adding `markupsafe ="~2.0.1"` would fix this. If that's fine for you, please let me know and I will create a pull request. 

In case it's preferred to use Markupsafe's new version 2.1.0, F-UJI would have to be updated to work with Flask 2 I believe. 

Thanks!

**Comment by huberrob** [comment]
Yes, this sounds good.. please go ahead and create the pull request
Thanks!
