### ISSUE TITLE
Open or restricted access to CC licenced data

### ISSUE THREAD

**Issue by huberrob** [pangaea-data-publisher/fuji#26]
Found here:

https://creativecommons.org/faq/#can-i-share-cc-licensed-material-on-password-protected-sites

Can I share CC-licensed material on password-protected sites?
Yes. This is not considered to be a prohibited measure, so long as the protection is merely limiting who may access the content, and does not restrict the authorized recipients from exercising the licensed rights. For example, you may post material under any CC license on a site restricted to members of a certain school, or to paying customers, but you may not place effective technological measures (including DRM) on the files that prevents them from sharing the material elsewhere.

**Comment by huberrob** [comment]
So creaticecommons does not guarantee access is possible -> removed from access rights check

**Comment by kitchenprinzessin3880** [comment]
i want to keep this issue open as this was overlook by FAIR principle. the distinction between access right and usage rights should be made clear..
