### ISSUE TITLE
How to disable basic auth locally

### ISSUE THREAD

**Issue by afuetterer** [pangaea-data-publisher/fuji#260]
Hi,

I struggle a bit with disabling basic auth locally. I see, that you added a key in the server.ini, that defaults to true.
https://github.com/pangaea-data-publisher/fuji/blob/9ca8fe68727fa6154f4828cc06633e324c857e80/fuji_server/config/server.ini#L21

If I set it to `false`, I still get a 401 when posting to /evaluate.

The swagger.yaml sets basic auth for the evaluate path anyways, right?
https://github.com/pangaea-data-publisher/fuji/blob/9ca8fe68727fa6154f4828cc06633e324c857e80/fuji_server/yaml/swagger.yaml#L31

Is there a way to disable basic auth for all api paths via the server.ini file?

**Comment by huberrob** [comment]
I think this parameter is not used at all..
To disable basic auth, you have to delete the following lines for the evaluate operation  in 'swagger.yaml':
```
      security:
        - basicAuth: []
```
