### ISSUE TITLE
Internal Server Error 500 when querying URLs

### ISSUE THREAD

**Issue by jantau** [pangaea-data-publisher/fuji#261]
Hi,

on my local F-UJI server I get an Internal Server Error 500 when I query URLs (e.g. https://physionet.org/content/ptb-xl/1.0.1/).

The warning message states: UserWarning: "https://physionet.org/content/ptb-xl/1.0.1/" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.

Do you know how I can fix this problem? The F-UJI web demo is able to handle the URLs I want to query.

**Comment by huberrob** [comment]
Thanks for the hint, the reason is a wrong import I will proved a fix asap..
