### ISSUE TITLE
Web Tool uses cached data?

### ISSUE THREAD

**Issue by stefaneichert** [pangaea-data-publisher/fuji#271]
Dear developers!
I am the developer of https://thanados.net and currently trying to implement FAIR metadata in the landing page of the entities provided by our web application as JSON LD.
I tried to assess the datasets via your web service https://www.f-uji.net/index.php and got a 47% on this example:
https://thanados.net/entity/50505
In the meantime I did some tweaks and added more metadata. So the result should be slightly better. 
When I tested it again, still the same result showed up.
I tested other datasets with the same amount of metadata in the same format e.g. https://thanados.net/entity/46927 and got  
4% : with only "FsF-F1-01D-1 | Identifier is resolvable and follows a defined unique identifier syntax (IRI, URL)"

The markup validation at schema.org shows now errors for both datasets and the same amount of metadata is provided, so I assume the syntax is correct.

Could it be that the web tool caches data?   

I tried it on several computers (Ubuntu 22.04, Win 10) with chrome and firefox and got the same results.

Thank you in advance and best regards,
Stefan

**Comment by stefaneichert** [comment]
Dear Robert,
thank you very much for the fast and helpful response. I removed the Dublin Core parts and followed your other suggestions as well. Now I reach 56%. :-)

However, I experienced a bit of a strange behaviour. As described above, I get different results for different entities with the same quantity and quality of of metadata on the same computer/browser. Entirely clearing the browsers cache/history and saved website data did not solve this. 

For example: https://thanados.net/entity/62811 reaches 56 % (Chrome as well as Firefox on Ubuntu 22.04)

![image](https://user-images.githubusercontent.com/6230720/170971236-3f59e2e0-97b9-4a41-b4b5-336d1dee56fd.png)

https://thanados.net/entity/50505 reaches 47% on the same machine with the same browsers:

![image](https://user-images.githubusercontent.com/6230720/170971433-2c8b9760-0cae-4860-9516-177f0fa7f7ad.png)

If I do the test on a completely other computer that never before accessed your webpage (Win 10, Firefox) in a different network I reach only 6% for the above mentioned entities even though the metadata are the same. 

![image](https://user-images.githubusercontent.com/6230720/170972613-d7fedf6e-5ee0-4189-aa98-2ac2f794141e.png)

Do you have any suggestion, what could cause this? If it is on my side or on yours?
Thank you again very much for the quick response and support!
Best wishes, Stefan

**Comment by huberrob** [comment]
Hallo Stefan

the different scores for the two datasets are probably due to a bug which is already fixed but not yet deployed on f-uji.net. At least the scores do not differ in my local environment.

The low score for thanados.net/entity/50505 is a result of the missing scheme in the URL you gave. F-UJI does not recognize this as a URL but instead thinks it is a handle. To avoid this add a scheme to the identifier (http, https).

best regards,
Robert
