### ISSUE TITLE
Change scoring for metadata FsF-F2-01M

### ISSUE THREAD

**Issue by huberrob** [pangaea-data-publisher/fuji#28]
sometimes metadata is found by the check and 'no metadata' is returned

**Comment by kitchenprinzessin3880** [comment]
the reason is that all partial elements ['creator', 'title', 'object_identifier', 'publication_date'] must present to be considered as 'partial metadata', otherwise 'no metadata' is returned.

**Comment by kitchenprinzessin3880** [comment]
i will check the debug message again...

**Comment by huberrob** [comment]
In my latest commit I simply changed the debug message from 'no metadata' to 'insufficient metadata' should be clearer now
