### ISSUE TITLE
FsF-F2-01M: change sequence of tests

### ISSUE THREAD

**Issue by huberrob** [pangaea-data-publisher/fuji#3]
Now we **always** perform **all** possible tests (og, schema.org. dc, datacite etc) to check for metadata in a 'from less to more imortant' sequence. But if we e.g. already have the complete set of required metadata from schema.org, there is no need anymore to call the datacite API or so.

I would therefore propose the following sequence:

First check for embedded schema.org metadata. If metadata is not complete check datacite. If is again not complete try some content negotiation to get some xml-rdf and get e.g. DCAT records.

Then get embedded DC, OG etc. as a fallback option

**Comment by kitchenprinzessin3880** [comment]
updated the sequence, see 'retrieve_metadata' method.

**Comment by kitchenprinzessin3880** [comment]
f57072104557dea57aa9affc620d2710f4fb9ea4

**Comment by huberrob** [comment]
Can we close this issue?

**Comment by kitchenprinzessin3880** [comment]
yup.
