### ISSUE TITLE
index.php is not updated

### ISSUE THREAD

**Issue by jcctesolin** [pangaea-data-publisher/fuji#317]
Hi guys,

Comparing the simple client embedded within f-uji server (index.php) with the one hosted in https://www.f-uji.net/, there is a difference in the assessment result, at the Summary box. While the former presents just a percentage as a result, the latter presents also pie chart.

![image](https://user-images.githubusercontent.com/86018252/212570277-667dfe31-1f4d-4781-a7a0-22a7b7937d86.png)
![image](https://user-images.githubusercontent.com/86018252/212570288-1b5dd327-ae6c-4521-8350-a8ca81d70add.png)

Is it possible to update it ?

Thanks

Julio

**Comment by huberrob** [comment]
the php client here is a little different from the f-uji.net web page, which does not include JS code.. so you will have to code this piece on your own (or c&p) from f-uji.net
