### ISSUE TITLE
F-UJI web client dataset assessment

### ISSUE THREAD

**Issue by ctmatsumoto** [pangaea-data-publisher/fuji#318]
Hello,

I'm not certain if this is the correct place to ask this question, but I didn't see any way to contact anyone on the web client.

I am trying to assess a dataset, which it seems like it did, having the message 'SUCCESS: FsF-A1-2M...'. My question is, is the assessment done? The 'processing wheel' keeps spinning but it's been spinning for 15 minutes. How long does an assessment normally take, understanding that this of course could change based on how large the dataset is. Also, what kind of output should I expect to see?

Thanks,

C.T. Matsumoto

**Comment by huberrob** [comment]
When the assessment is done, you should see a nice overview page showing the detailed assessment results for each metric.
If you do not see this, the assessment probably hangs. Can you please post the URL or PID of the dataset you are trying to assess so I can try to reproduce?

Robert

**Comment by ctmatsumoto** [comment]
Thanks,

Robert. I tried it on another computer. On that one it worked just as you described. Can I ask, is there a way I can use the API from a public client without installing the software?
________________________________
