### ISSUE TITLE
add namespaces

### ISSUE THREAD

**Issue by HeinkeH** [pangaea-data-publisher/fuji#324]
To improve I2-01M (more specifically FsF-I2-01M-2) we would like to add namespaces.

Unfortunately, it is rather unclear to us how to achieve this. Is this possible with JSON-LD or do we need additional forms of metadata? Can you provide us with an example?

We found an example which completely fulfilled I2-01M with `"is_namespace_active": true`:

https://doi.org/10.18743/DATA.00078

However, we were not able to understand how their metadata achieved this. Can you give us a hint about this? 
Best wishes
Heinke
-- 
Heinke Höck
World Data Center for Climate (WDCC)
Abteilung Datenmanagement

Deutsches Klimarechenzentrum GmbH (DKRZ)
Bundesstraße 45 a • D-20146 Hamburg • Germany

Phone: +49 40 460094-124
FAX:   +49 40 460094-270
[Email:hoeck@dkrz.de](mailto:Email:hoeck@dkrz.de)
URL:  [www.dkrz.de](http://www.dkrz.de/)

Geschäftsführer: Prof. Dr. Thomas Ludwig
Sitz der Gesellschaft: Hamburg
Amtsgericht Hamburg HRB 39784

**Comment by huberrob** [comment]
It depends on the metadata schema you use. But you need to use ontology terms in your metadata e.g as keywords or as part of the measured variables. 

The HTML from the example you gave contains a lot of links to metadata (link rel="alternate") files F-UJI probably followed for example this one:
https://researchdata.bbk.ac.uk/cgi/export/eprint/78/RDFXML/bbkdr-eprint-78.rdf 
I think this is where F-UJI found the usage of semantic resources.
