### ISSUE TITLE
Memory Leak on Docker Container

### ISSUE THREAD

**Issue by GonozalIX** [pangaea-data-publisher/fuji#335]
We are running FUJI as a docker container.
After a while the memory usage of each container is increasing a lot. 
I just restarted 3 containers running since 2 days  releasing 21 GB (!) of RAM. 
As a workaround we are restarting the containers if memory usage is above a certain level, nevertheless this should be fixed.

Maybe related to #120

**Comment by huberrob** [comment]
Thanks for the message, unfortunately I am not running F-UJi as docker container so I can't help here. However, there still might be some minor memory leaks left see #120 which may cumulate.. I'll leave this issue open, maybe someone else can help?
