### ISSUE TITLE
Remove yapf from pre-commit config

### ISSUE THREAD

**Issue by afuetterer** [pangaea-data-publisher/fuji#342]
Hi,

it is a pain to run the pre-commit hooks, because yapf is so slow. That encourages contributors to skip the hooks altogether.
Would consider switching to black (very opionated) and ruff (not a code formatter per se, but it can get a lot done).

Also the CI jobs using pre-commit fail after ~ 12 minutes. Which is way to long for a formatter.

What do you think? Do you need help with that?

**Comment by huberrob** [comment]
All these hooks have been provided a while ago and seem to be orphaned now. So I would be happy to have better/fixed hooks if you would provide any .. also the tests are outdated.

**Comment by afuetterer** [comment]
Alright, I would suggest using a combination of black and ruff nowadays. Those are pretty fast.

But black being black, is very opionated, it will change mostly all your files. Should I give it a try and look at the diff?

**Comment by afuetterer** [comment]
I will do that, can you fix the tests before I let the autoformatter change the files? #343
