### ISSUE TITLE
Remove outdated swagger.yaml files

### ISSUE THREAD

**Issue by afuetterer** [pangaea-data-publisher/fuji#346]
These files are out of date. It is confusing to have a file suffixed with "_old" in version control. Can they be removed?
- [fuji_server/yaml/swagger_auth.yaml](https://github.com/pangaea-data-publisher/fuji/blob/master/fuji_server/yaml/swagger_auth.yaml)
- [fuji_server/yaml/swagger_old.yaml](https://github.com/pangaea-data-publisher/fuji/blob/master/fuji_server/yaml/swagger_old.yaml)

**Comment by huberrob** [comment]
yes these files can be removed

**Comment by afuetterer** [comment]
Excellent, see corresponding PR #350.
