### ISSUE TITLE
reasoning for fuji_server/client

### ISSUE THREAD

**Issue by afuetterer** [pangaea-data-publisher/fuji#348]
The python modules in fuji_server/client are not part of the server, right? Are those tests or examples?
- [fuji_server/client/ex_evaluate.py](https://github.com/pangaea-data-publisher/fuji/blob/master/fuji_server/client/ex_evaluate.py)
- [fuji_server/client/fuji_test.py](https://github.com/pangaea-data-publisher/fuji/blob/master/fuji_server/client/fuji_test.py)

Should they be moved to examples/ or tests/?

**Comment by huberrob** [comment]
these are outdated and were for my own tests which accidently landed on git, will add to gitignore

**Comment by afuetterer** [comment]
I see, those confused me a bit. Thank you for handling it.
