### ISSUE TITLE
get_html_typed_links

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#37]
@huberrob 
{'url': href, 'type': l.attrib.get('type'), 'rel': l.attrib.get('rel'), 'profile': l.attrib.get('format')}
Cannot find 'format' attribute. Is this standard attribute of <link> rel?

**Comment by huberrob** [comment]
its from signposting where it is called 'formats' so it was never found and I think we do not need it..  can be deleted
