### ISSUE TITLE
Rename swagger to OpenAPI

### ISSUE THREAD

**Issue by afuetterer** [pangaea-data-publisher/fuji#386]
This project uses an OpenAPI specification, but still uses the old name "swagger". Should this be updated?

- https://github.com/search?q=repo%3Apangaea-data-publisher%2Ffuji%20swagger&type=code

**Comment by huberrob** [comment]
I think this is because the models are generated using swagger.io tools, so both is true but you are right OpenAPI is the relevant info

**Comment by afuetterer** [comment]
Alright, I think all manually inserted mentions of "swagger" like swagger API etc. can be replaced. The auto-generated files containing `swagger_items` should stay as they are.
