### ISSUE TITLE
Provenance Properties

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#39]
Mapping should be extended to cover the selected fields as follows (ref: https://www.w3.org/TR/prov-dc/)

Descriptive metadata | What | abstract, accrualMethod, accrualPeriodicity, accrualPolicy, alternative, audience, bibliographicCitation, conformsTo, coverage, description, educationLevel, extent, format, hasPart, isPartOf, identifier, instructionalMethod, isRequiredBy, language, mediator, medium, relation, requires, spatial, subject, tableOfContents, temporal, title, type
-- | -- | --
Provenance | Who | contributor, creator, publisher, rightsHolder
Provenance | When | available, created, date, dateAccepted, dateCopyrighted, dateSubmitted, issued, modified, valid
Provenance | How | accessRights, hasFormat, hasVersion, isFormatOf, isVersionOf, license, isReferencedBy, isReplacedBy, references, replaces, rights, source

'provenance' --> This leaves one very special term: provenance. This term is defined as a "statement of any changes in ownership and custody of the resource since its creation that are significant for its authenticity, integrity, and interpretation" [DCTERMS], a definition that corresponds to the notion of provenance for artworks. This term can be considered a link between the resource and any provenance statement about the resource, so it is not included in any of the aforementioned categories.

**Comment by kitchenprinzessin3880** [comment]
datacite relation types: 
IsSupplementTo
IsSupplementedBy
IsContinuedBy
Continues
IsDescribedBy
Describes
HasMetadata
IsMetadataFor
HasVersion
IsVersionOf
IsNewVersionOf

**Comment by huberrob** [comment]
Yes the DCTERMS 2 PROV mapping is very helpful!! Should have seen this before, now the code has to be changed a lot :(
Anyway it might be worth to do so. 
But in this case we should only use the direct mappings (tab 4 and 5) and also change the test output accordingly..

regarding DataCite relation types we query all but only use: 

process_indicators=['isVersionOf', 'isBasedOn', 'isFormatOf', 'IsNewVersionOf',
                            'IsVariantFormOf', 'IsDerivedFrom', 'Obsoletes']

list can be expanded... but also needs to be mapped to PROV

**Comment by huberrob** [comment]
Regardin DC2PROV mapping we can do this with terms which are also used by DataCite or schema.org. This would exclude e.g. terms like: accrualMethod, accrualPeriodicity, accrualPolicy  etc which I also have never seen in a dataset description. 
@kitchenprinzessin3880 do you agree?

**Comment by huberrob** [comment]
Descriptive metadata | What | abstract, accrualMethod, accrualPeriodicity, accrualPolicy, alternative, audience, bibliographicCitation, conformsTo, coverage, description, educationLevel, extent, format, hasPart, isPartOf, identifier, instructionalMethod, isRequiredBy, language, mediator, medium, relation, requires, spatial, subject, tableOfContents, temporal, title, type
-- | -- | --
Provenance | Who | contributor, creator, publisher, rightsHolder
Provenance | When | available, created, date, dateAccepted, dateCopyrighted, dateSubmitted, issued, modified, valid
Provenance | How | accessRights, hasFormat, hasVersion, isFormatOf, isVersionOf, license, isReferencedBy, isReplacedBy, references, replaces, rights, source
Provenance | Excluded | dct:abstract, dct:accessRights, dct:accrualMethod, dct:accrualPeriodicity, dct:accrualPolicy, dct:alternative, dct:audience, dct:available, dct:bibliographicCitation, dct:conformsTo, dct:coverage, dct:description, dct:educationLevel, dct:extent, dct:format, dct:hasPart, dct:identifier, dct:instructionalMethod, dct:isPartOf, dct:isRequiredBy, dct:language, dct:license, dct:mediator, dct:medium, dct:rights, dct:relation, dct:requires, dct:spatial, dct:subject, dct:tableOfContents, dct:temporal, dct:title, dct:type, dct:valid

**Comment by huberrob** [comment]
Code is now implemented, once the pull request is resolved I will close the issue..
