### ISSUE TITLE
reasoning for evaluate_config.yaml

### ISSUE THREAD

**Issue by afuetterer** [pangaea-data-publisher/fuji#396]
Hi,
what is the purpose of [fuji_server/yaml/evaluate_config.yaml](https://github.com/pangaea-data-publisher/fuji/blob/master/fuji_server/yaml/evaluate_config.yaml)?
The file has not been updated in a long time and from my searching it is not used by any other file or workflow.

**Comment by huberrob** [comment]
Uh one of the oldest files... I think it is not used and thus obsolete
