### ISSUE TITLE
How F-uji tool resolving typed link urls given in href to access linked metadata.

### ISSUE THREAD

**Issue by zhangyggesis** [pangaea-data-publisher/fuji#402]
1. Our test landing page https://searchtest.gesis.org/research_data/ZA3950 uses the typed link  `<link rel="describedby" type="application/ld+json" href="getScemaOrg.php?id=ZA3950">` to define the linked metadata.  

2. When we tested this landing page with the doi:  10.4232/0.test (whose landing page is https://searchtest.gesis.org/research_data/ZA3950 ) on F-uji tool.  F-uji tool resolved to the link  https://searchtest.gesis.org/research_data/services/getSchemaOrg.php?id=ZA3950 to access the linked metadata (see below). Therefore it could not find it, because the metadata is at https://searchtest.gesis.org/getSchemaOrg.php?id=ZA3950
3. 
![image](https://github.com/pangaea-data-publisher/fuji/assets/123384020/7bffc4c4-bcd0-4043-a6f9-7200588ac1b1)

4. I wonder how F-uji resolves the relative url  href="getScemaOrg.php?id=ZA3950" to https://searchtest.gesis.org/research_data/services/getSchemaOrg.php?id=ZA3950 .  

5. How href should be given in typed link ?

Thanks Yudong from Gesis.

**Comment by zhangyggesis** [comment]
@hvdsomp @huberrob  I wonder when you can help us with our questions? Yudong

**Comment by huberrob** [comment]
I think F-UJI only makes minimal attempts to handle incomplete paths, I will check if there is an issue with this. To be on the safe side you should use complete URLs instead.

**Comment by huberrob** [comment]
F-UJI is using urljoin which should do it correclty. I think you just forgot the leading slash, it should be href="/getSchemaOrg.php?id=ZA3950"

**Comment by hvdsomp** [comment]
Major thumbs up for the suggestion by @huberrob  to use complete URIs.

**Comment by zhangyggesis** [comment]
Thanks for the quick response. 

Regarding to using absolute link, here is the feedback from a member in our team:
 "We could use an absolute link. However, most other links are relative too and then resolve to the appropriate domain automatically, e.g. searchtest.gesis.org, search.gesis.org and localhost"

**Comment by huberrob** [comment]
I assume your team was clicking on links displayed by Chrome or another browser's dev-tool but this is buggy and not correctly interpreting RFC 1808. Generally: using browsers to test machine interoperability is not a good idea!
This document describes how relative links have to be resolved  and as far as I can see urljoin is implementing this quite nice:

https://www.ietf.org/rfc/rfc1808.txt

**Comment by zhangyggesis** [comment]
If the base url is `https://searchtest.gesis.org/research_data/ZA3950`, I can see from RFC1808 the difference between `href="/getSchemaOrg.php?id=ZA3950"` and `href="getSchemaOrg.php?id=ZA3950"` 

However, for `href="getSchemaOrg.php?id=ZA3950"` F-UJI tool used `https://searchtest.gesis.org/research_data/services/getSchemaOrg.php?id=ZA3950`  to access the metadata.  Where is the keyword  `service` in the path `.../service../` comes from ?

**Comment by huberrob** [comment]
This is indeed strange.. unfortunately I cannot reproduce this on my local installation which runs on the latest code which gives this warning - without /services/:

"_Request failed, status code -: https://searchtest.gesis.org/research_data/getSchemaOrg.php?id=ZA3950, text/turtle, application/turtle, application/x-turtle;q=0.8, application/rdf+xml, text/n3;q=0.9, text/rdf+n3;q=0.9,application/ld+json - 404_"

I assume this has something to do with the PID handling but since this error does not occur with the latest code I am not sure.
Anywy a good reason for me to speed up a bit and deploy a F-UJI > v.3 on f-uji.net

**Comment by zhangyggesis** [comment]
1. I tested this again today and "service" is no longer appear in the link.
2. our team member suspected that the issue is related to caching. 
3. The href had been changed from href="services/getSchemaOrg.php?id=ZA3950" -->  href="getSchemaOrg.php?id=ZA3950"
4. After the change to  href="getSchemaOrg.php?id=ZA3950" , "service" still appeared in the resolving link for a while, but it disappear today as I just tested it (see below.) 
![image](https://github.com/pangaea-data-publisher/fuji/assets/123384020/751f7cfc-3704-4212-a024-36ae7c2c0517)
5. Does F-UJI some how catching this ? it was getting the old href "services/getSchemaOrg.php?id=ZA3950".

**Comment by huberrob** [comment]
Yes F-UJI is caching responses.. this could be a reason for this behavior. 
Good hint., I think  have to check the lifetime of the cache, seems to exit much too long.. this also can cause memory problems.

**Comment by huberrob** [comment]
Ok I just found the caching problem, it seems as if it is not properly initialized before each test run.. will fix this for the next release

**Comment by zhangyggesis** [comment]
Thanks for the feedback. We look forward to your next release.
