### ISSUE TITLE
Replace deprecated python dependency: hashid

### ISSUE THREAD

**Issue by afuetterer** [pangaea-data-publisher/fuji#409]
[hashid](https://github.com/psypanda/hashID/releases/) had no updates since 2015, maybe switch one of the maintained forks (https://github.com/HashPals/Name-That-Hash, https://github.com/noraj/haiti)

**Comment by afuetterer** [comment]
@huberrob: Should hashid be replaced by Name-That-Hash? What do you think?

It is used only here:
https://github.com/search?q=repo%3Apangaea-data-publisher%2Ffuji%20hashid&type=code

**Comment by huberrob** [comment]
Jut realized I have not answered yet, sorry.... Name-That-Hash looks very good so why not!

**Comment by afuetterer** [comment]
Ref: https://github.com/HashPals/Name-That-Hash/wiki/API-Usage
