### ISSUE TITLE
OpenDAP support

### ISSUE THREAD

**Issue by huberrob** [pangaea-data-publisher/fuji#41]
We should add OpenDAP support. This is a very common protocol which is very common in earth and envronmental sciences. .. and easy to implement since it supports content-negotiation :

We just need to send a header content-type: application/vnd.opendap

See also: https://docs.opendap.org/index.php/DAP4:_Specification_Volume_2#Content_Negotiation_and_Media_Types

**Comment by kitchenprinzessin3880** [comment]
+1, re3data includes option api of opendap too

**Comment by huberrob** [comment]
Hmm.. unfortunately sending a content-type or accept header doesn't work that easy or is not supported by all of them
BUT: OpenDAP supports suffix handling
e.g. replacing *.html with *.xml returns some XML
same with: replacing */html with */xml 

I have seen this behaviour also at some other metadata providers so maybe we should try this generally?

**Comment by huberrob** [comment]
This is now somehow implemented using the def get_guessed_xml_link(self) method in fair_check
