### ISSUE TITLE
Metadata uses common semantic resources

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#44]
This metric should be further extended by distinguishing 'data model' vocabularies (e.g., dcat) from 'content vocabularies' (e.g., pato, envo, P01).

**Comment by huberrob** [comment]
Based on namespaces for metadata standards listed in fuji_server/data/metadata_standards_uris.json we could check and exclude..

**Comment by huberrob** [comment]
I have seen this is already implemented and a 'Default vocabulary namespace(s) excluded' INFO message is sent to the logger if e.g. default namespace was found from the list defined in data/default_namespaces.txt
