### ISSUE TITLE
PROV-O defined in JSON-LD not recognized

### ISSUE THREAD

**Issue by zhangyggesis** [pangaea-data-publisher/fuji#452]
In the JSON-LD of a Gesis test landing page: https://searchtest.gesis.org/research_data/ZA3950 (JSON-LD is provided via typed linke<link rel="describedby" type="application/ld+json" href="/getSchemaOrg.php?id=ZA3950"> i.e. https://searchtest.gesis.org/getSchemaOrg.php?id=ZA3950 )

A PROV-O entry is defined in the JSON-LD as
`
{"@context":[https://schema.org/,{"prov":[http://www.w3.org/ns/prov#](http://www.w3.org/ns/prov)}] ….} ,

"prov:wasRevisionOf":[{"@id":https://doi.org/10.4232/1.10078}]
`
However, when assessing this landing page with Fuji tool, it got no score for FsF-R1.2-01M-2 (see below)

**FsF-R1.2-01M-2 | Metadata contains provenance information using formal provenance ontologies (PROV-O) | 0**

**INFO | Check if provenance specific namespaces are listed in metadata 
WARNING | Formal provenance metadata is unavailable**

@huberrob @hvdsomp We wonder why the PROV-O definition in JSON-LD is not recognized by Fuji tool.   Can you please help?

Yudong from Gesis

**Comment by huberrob** [comment]
seems to be a bug in F-UJI , I will check..

**Comment by zhangyggesis** [comment]
Thanks for the feedback!  We look forward to checking result.

**Comment by zhangyggesis** [comment]
@huberrob  I wonder if you have any news regarding this so far? Thanks.

**Comment by huberrob** [comment]
I found the issue and fixed it but testing and deployment will take some time

**Comment by zhangyggesis** [comment]
Thanks!  I wonder when the bug fix could be deployed, therefore we can see result from the PROV-O definition in our JSON-LD.

**Comment by huberrob** [comment]
It should be available now at f-uji.net please check..

**Comment by zhangyggesis** [comment]
We tested it and it worked.  Many thanks !
