### ISSUE TITLE
[Bug]: missing file fuji_logo_square.png used by simpleclient/index.php .

### ISSUE THREAD

**Issue by marioa** [pangaea-data-publisher/fuji#453]
This should be a trivial fix.

The sample client: `simpleclient/index.php` has a reference to a logo image:

```html
<img src="/icon/fuji_logo_square.png" alt="" width="30" height="30" class="d-inline-block align-text-top">
```

but the logo file is not included in the distribution. It could just be added to `simpleclient/icon/fuji_logo_square.png` to the repo.

**Comment by huberrob** [comment]
Ok, icons are now included, thanks for spotting this!
