### ISSUE TITLE
Question about performing a FAIRness assessment on locally available and/or confidential data

### ISSUE THREAD

**Issue by epanagou-ubitech** [pangaea-data-publisher/fuji#456]
Hello, we have a quick question.

Is it possible to use F-UJI to perform a FAIRness assessment on data that is only available locally and does not have a persistent identifier due to its confidential nature?

Thank you in advance.

**Comment by huberrob** [comment]
Yes of course but the result will depend on the overall accessibility. You can also try to run F-UJI on your own server and in case your data is protected by HTTP Basic Auth you can use the auth token to assess protected data.

**Comment by epanagou-ubitech** [comment]
Thank you for the quick and helpful answer! We have a few follow up questions:

Are we correct to assume that F-UJI also extracts metadata from the landing page of datasets available, for example, in Zenodo?

If yes, how would that work (or not work) when using a private dataset? Is there any way to provide such metadata to F-UJI without publishing the dataset to such a platform?

**Comment by huberrob** [comment]
Please take a look here https://f-uji.net/index.php?action=methods to understand how F-UJI collects metadata.

And sorry but I don't understand the context, do you expect the dataset(s) to be FAIR despite all metadata is hidden? That won't work. If you hide your metadata, F-UJI won't find it. 

But  if you what to e.g. analyse your data internally you would have to install F-UJI in your local environment (network) and there allow more insights to your metadata do F-UJI ca see it locally within your protected environment.

**Comment by epanagou-ubitech** [comment]
That is clear, thank you for your answer.
