### ISSUE TITLE
[Bug]: Server not responding!?

### ISSUE THREAD

**Issue by matschwa** [pangaea-data-publisher/fuji#485]
The server does not responde the queries.

## Description

Copy past a random URL/DOI from Zendo in to the f-uji assessment tool; start assessment → observe error
![grafik](https://github.com/pangaea-data-publisher/fuji/assets/31959308/1696f68d-5581-4a78-9ab2-72e339d82fb1)

## Expected Behavior

Results of FAIR Assessment
## Actual Behavior

Server does not respode

## Steps to reproduce

1. Copy past a random URL/DOI from Zendo in to the f-uji assessment tool; 
2. start assessment 
3. → observe error

## Your Environment

- `python --version`
- `pip show fuji | grep "^Version\:"`

**Comment by huberrob** [comment]
F-UJI crashed but is running again now, thanks for the hint
