### ISSUE TITLE
Data file format checks

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#49]
In current implementation, only file formats of active content urls are considered.  there can be a case where the format is specified in the metadata but the data content url is missing. there should be a debug message indicating it.
example of data: ttps://hdl.handle.net/10411/G8MPEI

**Comment by huberrob** [comment]
Now the code raissing a warning log message such as: 
WARNING: Object (content) url is empty - {'type': 'text/csv', 'size': 1143551}",
