### ISSUE TITLE
Mapping between the metadata in schema.org Json LD and each of the metric tests in Fuji tool analysis using https://www.f-uji.net/index.php

### ISSUE THREAD

**Issue by zhangyggesis** [pangaea-data-publisher/fuji#536]
We are helping a partner to increase the fairness of their research data.  

They would like to have a mapping between schema.org Json LD metadata to each of the metric tests in the Fuji tool analysis.   Therefore they can use this mapping as a basis to see what metadata they can provide to improve their scores/fairness. 

I wonder if you have this kind of mapping, if yes,  can you please provide them to us.

Many thanks in advance.

Yudong form Gesis.

**Comment by huberrob** [comment]
No, there is no such mapping. However, you can take a look at SCHEMAORG_MAPPING in metadata_mapper.py which is a (now deprecated) JMESPATH  for embedded, simple JSONLD content. This should give you at least an idea which properties are mapped.

**Comment by zhangyggesis** [comment]
Great thanks! I have informed our partner regarding this. Yudong
