### ISSUE TITLE
Opening very large compressed (tar.gz) files slows the test extremely

### ISSUE THREAD

**Issue by huberrob** [pangaea-data-publisher/fuji#54]
We should test file size before download and exclude very large archives
See for example doi:10.17882/42182
which provides a > 30 Gb file

**Comment by kitchenprinzessin3880** [comment]
yup, the size property would be useful here ;)

**Comment by kitchenprinzessin3880** [comment]
related work, the config file now has a parameter 'data_files_limit' to set the number of max files to be processed usign apache tika.

**Comment by huberrob** [comment]
Changed code so content is retrieved as stream now. F-UJI skips now after timeout is reached (10 sec).
