### ISSUE TITLE
Bugs Found

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#57]
Commented by @ajaunsen Here are some datasets that caused the evaluator to crash

- [x] https://su.figshare.com/articles/Data_for_Does_historical_land_use_affect_the_regional_distribution_of_fleshy-fruited_woody_plants_Arnell_et_al_2019_/10318046 | KeyError: 'object_size'

- [x] https://datasets.aida.medtech4health.se/10.23698/aida/brln | AttributeError: 'dict' object has   no attribute 'decode'

- [x] https://services.fsd.uta.fi/catalogue/FSD3263 | KeyError: 'object_size'

- [x] https://usn.figshare.com/articles/Data_Journal_EvolutionaryApplications_RData/7770785 | KeyError: 'object_size'

**Comment by kitchenprinzessin3880** [comment]
Re3data is misspelled as R3DATA
* some of the tests seem to rely on extracting information from re3data.org, but this is either not working or not robust enough, because it fails although I know the repository is listed in re3data.org (e.g. snd.gu.se)
* I am not sure I understand what metric 6 is expecting to find (access level/conditions)?
* in the debug output, there are various examples of confusing use of 'data', when it seems to me it is meant ‘dataset’
* metric 11 (license), it would make sense to add additional score if the license can be resolved (btw. I am not familiar with the SPDX license repr.)

**Comment by kitchenprinzessin3880** [comment]
> Here are some datasets that caused the evaluator to crash
> 
> https://su.figshare.com/articles/Data_for_Does_historical_land_use_affect_the_regional_distribution_of_fleshy-fruited_woody_plants_Arnell_et_al_2019_/10318046 | KeyError: 'object_size'
> 
> https://datasets.aida.medtech4health.se/10.23698/aida/brln | AttributeError: 'dict' object has no attribute 'decode'
> 
> https://services.fsd.uta.fi/catalogue/FSD3263 | KeyError: 'object_size'
> 
> https://usn.figshare.com/articles/Data_Journal_EvolutionaryApplications_RData/7770785 | KeyError: 'object_size'

bugs related to key 'object_size' is fixed. @https://github.com/pangaea-data-publisher/fuji/commit/2a3c0160fcad1eb82bcfaddddc016114c0ee526a

**Comment by kitchenprinzessin3880** [comment]
Re3data is misspelled as R3DATA 
fixed @ https://github.com/pangaea-data-publisher/fuji/commit/addd99988a9d46570aadbe8c7dd130108da723c4

**Comment by kitchenprinzessin3880** [comment]
> * AttributeError: 'dict' object has   no attribute 'decode'

fixed @ https://github.com/pangaea-data-publisher/fuji/commit/e6f9f2a234f7550a08760eb7e8653eef442f9580

**Comment by kitchenprinzessin3880** [comment]
> * some of the tests seem to rely on extracting information from re3data.org, but this is either not working or not robust enough, because it fails although I know the repository is listed in re3data.org (e.g. snd.gu.se)
With reference to re3data entry, https://www.re3data.org/repository/r3d100010146 no API information of the reposiroty is available. therefore the tool was not able to evaluate metrics related to metadata standards.

**Comment by kitchenprinzessin3880** [comment]
> * I am not sure I understand what metric 6 is expecting to find (access level/conditions)?
there is only one metric on accessibility (at present). It checks if the metadata includes access level of a dataset, e.g., public, embargoed, etc. the conditions depends on the level specified. If it is embargoed data, the date the dataset will be publicly released should be specified.

**Comment by kitchenprinzessin3880** [comment]
> * in the debug output, there are various examples of confusing use of 'data', when it seems to me it is meant ‘dataset’
i have opened a separate issue to address this requirement: https://github.com/pangaea-data-publisher/fuji/issues/59

**Comment by kitchenprinzessin3880** [comment]
> * metric 11 (license), it would make sense to add additional score if the license can be resolved (btw. I am not familiar with the SPDX license repr.)

i have opened another issue (labelled as enhancement) to address this requirement, see https://github.com/pangaea-data-publisher/fuji/issues/60
it is launched by linux foundation; Datacite suggests the use the identifiers from the SPDX licence list for representing license metadata, see https://schema.datacite.org/meta/kernel-4.3/ (page 27)
for more info about spdx license. see https://spdx.org/licenses/

**Comment by mfenner** [comment]
Reasons for SPDX:

* human-readable string for the license, e.g. for search facets
* good library support in multiple languages
* good coverage of relevant open licenses

In principle the license URL would also work, but there are too many variations, e.g. for Creative Commons licenses. Also, a URL is not easily made human-readable. I am not aware of strong alternatives, other than rolling your own implementation.

**Comment by kitchenprinzessin3880** [comment]
+1 @mfenner 
also the license information is available in different formats at different expressiveness level, see https://github.com/spdx/license-list-data

**Comment by ajaunsen** [comment]
OK, issues addressed. Thx!
Ticket can be closed.
