### ISSUE TITLE
Extend the tests related to license information

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#60]
@ajaunsen 
it would make sense to add additional score if the license can be resolved.

**Comment by kitchenprinzessin3880** [comment]
another suggestion related to license provided by Evgeny (https://www.fairsfair.eu/fairsfair-data-object-assessment-metrics-request-comments)

in some instances the metrics unpack the FAIR criteria further to reach dichotomic decision, which I support. Here, however, as in some other cases, this is not the case. I would recommend to unpack this metric further, or else I would not know how to apply it. One suggestion: (i) standard or bespoke license and (ii) machine-readability of license. In some instances I also see license information mentioned once for the whole repository rather than for every dataset. It is not good practice, and often it is confusing whether this relates to datasets or the database as such, but this could potentially be another metric before the other two.

**Comment by huberrob** [comment]
According to the conversation in  #57 an additional scoring for discoverabiloity/availability in SPDX could be added. 
I will raise the total score of this test to two: one for licence availability one for SPDX listing.
