### ISSUE TITLE
OpenAIRE Explore/Graph - Potential Registry to Support Automated FAIR Data Assessment.

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#61]
Source: OpenAIRE EXPLORE 
https://beta.explore.openaire.eu/search/dataset?datasetId=datacite____::e95c6f777dcef1498cd1cb16b4574746

API information: https://develop.openaire.eu/api.html#datasets

Example of dataset search: http://api.openaire.eu/search/datasets?doi=10.7925/drs1.duchas_4474990

**Comment by kitchenprinzessin3880** [comment]
@huberrob - we have already using datacite content-negotiation, but if openaire registry includes metadata of datasets from other PID providers this might be a good resource to apply to support F-UJI automated assessment. Further exploration is required in terms the registry's coverage and metadata schema.
We need to consult with @mfenner

**Comment by huberrob** [comment]
I think this registry is very different from DataCite which requires **active** registration (push) by DOI issuers. OpenAire seems to collect metadata from some resources (pull) we should not use this as source for metadata.

Maybe we can use this for FsF-F4 instead?

**Comment by huberrob** [comment]
In the moment I think F-UJI should not rely on too many external resources. This would bias FAIR testing. If a data set is not FAIR 'by nature' this cannot be solved by external resources but has to be done by the data set publisher.
