### ISSUE TITLE
Schema.org Types Suported

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#62]
@ajaunsen 

Evaluating e.g. 
https://www.proteinatlas.org/ENSG00000110651-CD81/cell
 
Metric 5 claims no JSON-LD is found.

Metric 3 reports:
      "INFO: Found JSON-LD schema.org but record is not of type \"Dataset\””,

Investigating the content I find there is indeed a ld+json object, but of type=“DataRecord”. Not sure if this is a previous type of schema.org that has become deprecated or what… but the data provider clearly has defined structured data according to some schema.org form.

**Comment by kitchenprinzessin3880** [comment]
F-UJI only accepts two types of resources ‘Dataset’ and ‘Collection’ from schema.org as we focus on research data. There is no type called ‘DataRecord’, at least in the current version of schema.org. I checked the page also with google validator tool, see below error below. 

I notice that the ‘DataRecord’ is draft type from bioschema.org : https://bioschemas.org/types/DataRecord/0.3-DRAFT-2019_06_20/
Since this is still draft, I don’t think at this stage F-UJI will be extended to evaluate datasets described via the bioschema profile of schema.org. 

![a](https://user-images.githubusercontent.com/11935313/93761896-e16d4d80-fc0e-11ea-8f90-eecd6d29d158.png)

**Comment by huberrob** [comment]
I agree we should not  (yet) add the draft type DataRecord to the test. 
According to the DataRecord specs it is derived from Dataset and the only additional property is 'includedInDataset'. This most likely will not be approved since such a relation already hcan be handled by the standard Dataset property 'isPartOf'
