### ISSUE TITLE
re3data (repository records are not detected)

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#63]
Comments from @ajaunsen

some of the tests seem to rely on extracting information from re3data.org, but this is either not working or not robust enough
examples:

- [x] snd.gu.se
This is the dataset I tested: 
https://snd.gu.se/en/catalogue/study/snd1038

- [x] metric 13 also fails for e.g. DataDOI which is listed with OAI-PMH API on re3data.org:
https://datadoi.ut.ee/handle/33/152

**Comment by kitchenprinzessin3880** [comment]
@ajaunsen this identifier is broken https://datadoi.ut.ee/handle/33/152

**Comment by kitchenprinzessin3880** [comment]
The test debug of https://snd.gu.se/en/catalogue/study/snd1038 on metric 'FsF-R1.3-02D' 
The identifier above is not a pid, therefore the tool was not able to automatically discover the API  (e.g., oaipmh) information from re3data (through datacite repository api).
"test_debug": [
                "INFO: Retrieving API and Standards from re3data",
                **"INFO: re3data/datacite client id - None",**
                "INFO: Use OAIPMH endpoint to retrieve standards used by the repository **- None**",
                "WARNING: Unable to determine community standard"
            ],

**Comment by kitchenprinzessin3880** [comment]
> * metric 13 also fails for e.g. DataDOI which is listed with OAI-PMH API on re3data.org:
>   https://datadoi.ut.ee/handle/33/152

 @ajaunsen the identifier above is not a pid, therefore it was not possible to discover the oai-pmh endpoint automatically from datacite/re3data. i tested with its doi instead: http://dx.doi.org/10.15155/re-117

Here is the output of metric ''Metadata follows a standard recommended by the target research community of the data."

```
 "test_debug": [
                "INFO: Retrieving API and Standards from re3data",
                "INFO: re3data/datacite client id - estdoi.repo",
                "INFO: Skipping non-disciplinary standard listed in OAIPMH - Dublin Core",
                "WARNING: Unable to determine community standard"
            ],
```
Therefore the tool detected the endpoint and its metadata format (dublincore). since this metric is about community-based metadata standards, therefore the test against this metric is failed.

**Comment by ajaunsen** [comment]
OK, understood. Thanks for the info.
This issue can be closed.
