### ISSUE TITLE
Evaluations fail with KeyError: 'content-type'

### ISSUE THREAD

**Issue by ajaunsen** [pangaea-data-publisher/fuji#66]
Following examples of datasets from 3 different repositories fail with this error:

https://usn.figshare.com/articles/Data_Journal_EvolutionaryApplications_RData/7770785
https://data.dtu.dk/articles/Data_for_the_paper_A_dual_reporter_system_for_investigating_and_optimizing_translation_and_folding_in_E_coli_/10265420
https://su.figshare.com/articles/Data_for_Does_historical_land_use_affect_the_regional_distribution_of_fleshy-fruited_woody_plants_Arnell_et_al_2019_/10318046

**Comment by huberrob** [comment]
Thanks for the hint.. this is fixed now see: https://github.com/pangaea-data-publisher/fuji/pull/64/commits/f90aac161848df57f7cd79a2aaf66f72754b913d

Needs to be merged to master.
