### ISSUE TITLE
Schema.org (publisher vs provider)

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#67]
publisher -(https://schema.org/publisher) The publisher of the creative work.
provider (https://schema.org/provider): The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.

Are they same in the context of dataset?

**Comment by kitchenprinzessin3880** [comment]
@https://github.com/ashepherd @uschindler Any idea?

**Comment by ashepherd** [comment]
hi @kitchenprinzessin3880 they could be the same and at BCO-DMO they are, but we do have use cases where another data repository, LTER for example,  is the publisher, but we provide discovery and access to those data. In those cases the schema:publisher => LTER and schema:provider => BCO-DMO (for the webpage at BCO-DMO). If LTER is also providing the data, they probably have markup saying schema:publisher => LTER and schema:provider => LTER. Does that make sense or help?

**Comment by kitchenprinzessin3880** [comment]
@ashepherd +1 (the difference is obvious at metadata aggregator level). Thanks ;)

**Comment by uschindler** [comment]
At PANGAEA we use publisher for ourselves which also goes in line with the classical semantics of a publisher: "scientists publish their dataset through PANGAEA" like "scientists publish their article through Science/Nature".
This also goes in line with Datacite metadata and Dublin core and various Citation formats.

We also fill in dataCenter (but with same information).

Provider is not used by us and makes not too much sense in scientific use-case, only for aggregators: Datacite could fill in themselves when they provide metadata on their search catalogue. But that's unimportant for science as it brings not much more information for Enduser. In short: on original data center, no provider should be given.

**Comment by kitchenprinzessin3880** [comment]
thanks uwe. i have modified the mapping accordingly (use publisher first, if it is not available use provider).
