### ISSUE TITLE
Extend related resources check with PID graph entities

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#68]
A dataset can be an 'orphan' dataset, w/o links to its related datasets or publications. The practical test should be extended to include other research assets identified by PID besides datasets and publications.

**Comment by kitchenprinzessin3880** [comment]
@huberrob (previous comment, Some datasets may be isolated by design)

**Comment by huberrob** [comment]
We will cover parts of this using the signposting approach. But we cannot do more. Can I close this issue?

**Comment by huberrob** [comment]
Merged with #65
