### ISSUE TITLE
What to do with relative URL paths in e.g. signposting?

### ISSUE THREAD

**Issue by huberrob** [pangaea-data-publisher/fuji#7]
Sometimes we have relative paths indicating e.g. in <link> tags paths to object_identifier_content?
Will we accept these as valid identifiers? Or only if they resolve?

**Comment by kitchenprinzessin3880** [comment]
Can you please provide some examples?

**Comment by huberrob** [comment]
Here is an examp,e which inludes relative paths to representations of metadata:

https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-tests-de-depistage-de-covid-19-realises-en-laboratoire-de-ville/

For example:

<link rel="alternate" type="application/rdf+xml" href="/datasets/5e7de8cf4663c08d4f74ba01/rdf.xml" />

Using the self.landing_origin attribute I introduced in my last commit, we simply can check if a href string is an URL or not. If not we can check if href starts with '/' and if  so expand the URL by appending href to landing_origin. 
This could be done in method get_html_typed_links see     #10

**Comment by huberrob** [comment]
get_html_typed_links method now completes relative paths with relevant URL authority part..
