### ISSUE TITLE
Metadata element 'Language' should be checked

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [pangaea-data-publisher/fuji#71]
Related doc: 
https://www.w3.org/International/questions/qa-text-processing-vs-metadata
https://www.w3.org/International/getting-started/language

**Comment by huberrob** [comment]
I think in the moment the descriptive metadata part is almost finished. But maybe this could be part of another metric such as 'content/metadata is provided in a way **humans** can read and understand'.

**Comment by huberrob** [comment]
http://purl.org/dc/terms/language also in DCAT
https://schema.org/inLanguage
DDI: several places 
/codeBook/@xml:lang
RDF Literal lang attribute
