### ISSUE TITLE
Few questions to better understand the F-UJI Tool

### ISSUE THREAD

**Issue by wilkos-dans** [pangaea-data-publisher/fuji#74]
Hi F-UJI team, for a better understanding of the F-UJI tool in DANS, but also Synergy, I have a few questions regarding the tool. Hope you can help us.

1. Apart from https://www.fairsfair.eu/f-uji-automated-fair-data-assessment-tool, is application documentation available? I think I read something about it comming available soon? Perhaps the slides used in the presentation given last week (Talk & Demo on FAIRsFAIR Tool (F-UJI)) are available?
 
1. Can Fuji assess individual metrics, or does it always perform all of the 14 provided metrics?
 
1. Which external services/API's is FUJI checking? i.e: re3data, datacite?
Are all these listed in /config/server.ini?
 
1. What is the impact on the result if, or if not, an oai-pmh-endpoint (oaipmh_endpoint) is provided in the input?
 
1. What does total score per metric: "total_score": 4, mean? Does it represent the number of tests that are performed?
 
Q: "score": {
"earned": 1,
"total": 4
} "test_status": "fail"
 
Moreover, is there a relation between 'earned' and 'total points', and the test_status outcome (pass/fail)?

Thanks in advance.

**Comment by kitchenprinzessin3880** [comment]
> 1. Apart from https://www.fairsfair.eu/f-uji-automated-fair-data-assessment-tool, is application documentation available? I think I read something about it comming available soon? Perhaps the slides used in the presentation given last week (Talk & Demo on FAIRsFAIR Tool (F-UJI)) are available?

Here you go: https://zenodo.org/record/4068347#.X33ZJGgzabg

**Comment by kitchenprinzessin3880** [comment]
> * Which external services/API's is FUJI checking? i.e: re3data, datacite?
>   Are all these listed in /config/server.ini?
> *

yes, the link available in the config file https://github.com/pangaea-data-publisher/fuji/blob/master/fuji_server/config/server.ini
