### ISSUE TITLE
versioning of FUJI tool

### ISSUE THREAD

**Issue by ajaunsen** [pangaea-data-publisher/fuji#78]
Versioning of the tool should be enabled and incremented automatically with every revision so that users can have a way of knowing if two evaluations have been executed using the same version.

This requires the JSON output to include info about the version. It may be useful to have versions of tests/metrics and harvester – or simply one version that reflects any changes at any level.

**Comment by kitchenprinzessin3880** [comment]
Hi Andreas, 
the information is captured through 'metric_specification' which has the version number.

**Comment by huberrob** [comment]
I agree that software versions make a difference, each one might perform the evaliuations differenetly e.g. due to bug fixes etc.

**Comment by ajaunsen** [comment]
Hi Anu,
Looking at the 'metric_specification’ this points to a DOI redirecting to a versioned document on zenodo.org on the metrics. This is useful, but not in the context I mentioned. In the case I mentioned you would like to know the exact software version that a result file / JSON output was produced by so that it can be understood if two outputs were produced by the exact same software version.

This would imply that any minor change of a single piece of code would require a new software version… tedious perhaps (and a short change log would need to follow each edit), but necessary if the FUJI tool is to be used for large-scale evaluations – at some point comparisons of results between versions will be required to debug or trace down issues, or to understand differing results on same datasets.
> the information is captured through 'metric_specification' which has the version number.
> 
Cheers,
Andreas

**Comment by kitchenprinzessin3880** [comment]
Hi Andreas,
The exact version of the software has been recorded here https://github.com/pangaea-data-publisher/fuji/releases following https://semver.org/. I agree with you, the version information should be recorded at more granular levels (not only major releases). fyi, @huberrob 
Btw, I hope you had great holidays ;) i am now stuck in the quarantine hotel (down under).

**Comment by ajaunsen** [comment]
OK, great that the you guys agree on this. Two changes would be needed; a) higher granularity of software versioning and b) including version info in the results output (for provenance).

Andreas

**Comment by huberrob** [comment]
JSON output now has a software_version info ..
