### ISSUE TITLE
WARNING on not-OK (non-200) http request returns?

### ISSUE THREAD

**Issue by ajaunsen** [pangaea-data-publisher/fuji#90]
On occasion some GUIDs may deprecate or temporarily become unavailable, leading for instance to a http request error 404 or similar.

Example; http://fel.hi.is/cultural_scales

In such cases it would be beneficial to warn in the output of the evaluation that there is potentially a problem with the site (instead of evaluating the error page).

**Comment by ajaunsen** [comment]
I should add, something like this seems to be done for FsF-F2-02D, but not on URIs (in FsF-F1-01D).

**Comment by huberrob** [comment]
should be solved now
