### ISSUE TITLE
Datasets that crash the evaluator

### ISSUE THREAD

**Issue by ajaunsen** [pangaea-data-publisher/fuji#93]
These datasets cause a '500 internal server error' when running the FUJI evaluator on them:

https://data.geus.dk/Marta2/sejllinje.jsp?lineid=20662
https://data.geus.dk/Marta2/survey.jsp?surveyid=1220

**Comment by huberrob** [comment]
content decoding bug .. fixed in next merge

**Comment by ajaunsen** [comment]
Similar issue with:
https://ortus.rtu.lv/science/en/datamodule/294
https://ortus.rtu.lv/science/en/datamodule/121

**Comment by huberrob** [comment]
Same bug.. addressed as well in https://github.com/pangaea-data-publisher/fuji/commit/eaa0cb50fae30ccbb2cfe5a3f20fbf4f7c7b0005

**Comment by huberrob** [comment]
@ajaunsen the ortus.rtu.lv examples contain JSON-LD encoded DCAT metadata which is nice. But this DCAT cannot be parsed because an array is used where it should not be. Maybe the RTU team can fix this? Are you in touch with them?

**Comment by ajaunsen** [comment]
@huberrob sure, I have sent our contact at RTU a message about this. Let’s see what they do.

Andreas

**Comment by huberrob** [comment]
Bugs have been fixed so I'll close this issue.
